### PR TITLE
Add itemsPerPage field in album manager page

### PR DESCRIPTION
**Pull request by danyaPostfactum**
I have faced with such problem: I had to sort items, there is no problem to sort items within one page, but I did not find the way to do it between two pages, so I have added field "Items per page" to bottom paging bar, like one under MODx system settings grid (for example).

Additionally, default value for this field is taking from default_per_page system setting

### CODE REVIEW

**Comment by splittingred** [comment]
Good suggestion! Thanks!

**Comment by danyaPostfactum** [comment]
It is nesessary to use  this.store.reload() instead of this.run(). this.run doesn't respect pageSize field value.

**Comment by splittingred** [comment]
Hm, ok; will get it in for the next fix.

**Comment by splittingred** [comment]
Fixed here: https://github.com/splittingred/Gallery/commit/02653f23b62b902a9d8a8ce1887b866effe29170

**Pull request closed without merging**
