### PR TITLE
[GalleryAlbums] Added containerTpl (with navigation placeholders) and totalVar placeholder

### PR DESCRIPTION
**Pull request by Jako**
containerTpl has the following navigation placeholders: nav.first, nav.prev, nav.current, nav.next, nav.last

Snippet could work with getPage now (but it is not changing the current gallery together with getPage).

### CODE REVIEW

**Comment by jpdevries** [comment]
Hi @Jako, if this gets added could you help us update the docs?

this is in the new branch over at modxcms/Gallery
https://github.com/modxcms/Gallery/commit/4e8207cfa3d7be5ac1bedcffb85c5049308b92d0

**Comment by Jako** [comment]
Sure.

**Comment by Jako** [comment]
Where should I help you to update the docs? On RTFM?

**Comment by jpdevries** [comment]
That would be great @Jako if you could help us update RTFM. I am not sure were we are with granting editor access to RTFM, we may be able to do that for you. I will look into that Monday. If not just letting us know what in the docs should be updated would also work.

**Comment by Jako** [comment]
I have already access there. Seems I could edit the Gallery docs, but maybe I cannot save them.

**Comment by jpdevries** [comment]
Uh oh. Sounds like there could be a bug or permissions issue. Could you note *added in version for new features? I think that is a good way to be able to update docs before the version is done being tested. 

We can of course instead not publish the update until the next release. 

—

**Comment by Jako** [comment]
Did not tried that yet. If I fail during editing I will ask Jay.

I will prepare my doc changes for next Gallery update and change it, when it is published.

**Comment by jpdevries** [comment]
Sounds good. Thanks!

—

**Comment by Jako** [comment]
Updated RTFM.

**Comment by jpdevries** [comment]
Awesome. Thanks!

—

**Pull request merged**
