### PR TITLE
Add support for selection of album cover.

### PR DESCRIPTION
**Pull request by Indomian**
Can use image from gallery or upload a new one.
- Updated version to 1.5.3-a2 for package install purporses
  - Add new field to galAlbum model - cover_filename

Signed-off-by: Egor Bolgov egor.b@fabricasaitov.ru

### CODE REVIEW

**Comment by jpdevries** [comment]
@Indomian if this gets added it seems the docs should get updated. Could you help us with that? Got this merged into the new develop branch over at
modxcms/Gallery
https://github.com/modxcms/Gallery/commit/831747595ad71e6bfaeb1609d7c7961bbd391436

**Comment by Indomian** [comment]
@jpdevries can you get me a link to documentation editor so i can add new info once it's released?

**Comment by jpdevries** [comment]
@Indomian no problem, can you shoot me an email to jp@modx.com?

**Comment by Indomian** [comment]
@jpdevries done

**Pull request merged**
